version: "2.3"

services:
  
  # ROS Melodic Orbbec Astra docker
  astra:
    image: husarion/astra:latest
    restart: unless-stopped
    environment:
      - "ROS_IP=astra"
      - "ROS_MASTER_URI=http://my-ros-master:11311"
    devices:
      - /dev/bus/usb/001/006
    tty: true        
    command: roslaunch astra_camera astra.launch