services:

  # ROS Melodic
  rosbot_simulation:
    image: husarion/rosbot:melodic-simulation
    container_name: rosbot-amcl-simulation
    runtime: nvidia
    network_mode: "host"
    tty: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - ~/launch:/ros_ws/src/rosbot_description/launch
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: roslaunch rosbot_description rosbot_amcl_headless.launch