services:

  localization:
    image: husarion/slam-toolbox:galactic 
    container_name: slam-toolbox
    restart: unless-stopped
    volumes: 
      - ./config/slam_params.yaml:/slam_params.yaml
      - ./maps:/maps
    command: >
      ros2 launch slam_toolbox online_sync_launch.py 
        slam_params_file:=/slam_params.yaml