services:

  # ROS Galactic
  rviz:
    image: husarion/rviz2
    restart: on-failure
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_pro_mapping.rviz:/root/.rviz2/default.rviz
      # - ./config/rosbot_pro_localization.rviz:/root/.rviz2/default.rviz
    environment:
      - LIBGL_ALWAYS_SOFTWARE=1   # always use software rendering - to run rviz2 container
      - DISPLAY