services:

  # ROS Melodic
  rosbot_simulation:
    image: husarion/rosbot:melodic-simulation
    container_name: rosbot-gmapping-simulation
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./../src/rosbot_navigation/maps:/ros_ws/src/rosbot_navigation/maps
    command: roslaunch rosbot_description rosbot_rviz_gmapping.launch