# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

version: "2.3"

services:

  # ROS Galactic
  rviz:
    # image: husarion/rviz2
    image: husarion/nav2:galactic
    runtime: nvidia
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./../../nav2-docker/src/husarion_nav2/config/rosbot_pro_localization.rviz:/root/.rviz2/default.rviz
      # - ./../../nav2-docker/src/husarion_nav2/config/rosbot_pro_mapping.rviz:/root/.rviz2/default.rviz
    environment:
      - ROS_DOMAIN_ID=228
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: >
      ros2 launch nav2_bringup rviz_launch.py 
        rviz_config_file:=/root/.rviz2/default.rviz