services:

  # ROS Galactic
  localization:
    image: husarion/nav2:galactic
    restart: on-failure
    container_name: nav2-amcl
    volumes: 
      - ./config/amcl_params.yaml:/amcl_params.yaml
      - ./maps:/maps
    command: >
      ros2 launch nav2_bringup localization_launch.py
        params_file:=/amcl_params.yaml
        map:=/maps/map.yaml
