services:

  # ROS Melodic
  rosbot_simulation:
    image: husarion/rosbot:melodic-simulation
    container_name: rosbot-amcl-simulation
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rostest navigation_testing navigation_gui.test