name: Test ROS1 Navigation

on:
  push:
    branches:
      - 'ros1'
  # schedule:
  #   - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  test-navigation:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build and run tests
      run: docker run --rm husarion/rosbot:melodic-simulation rostest navigation_testing navigation.test
      

    
    
